---
apiVersion: v1
kind: Secret
metadata:
  name: acm-pull-secret
  namespace: open-cluster-management
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdG9yeS5jc2luLmN6Ijp7ImF1dGgiOiJjM2x6YjNCbGJuTm9hV1owTFdSbGNHeHZlVG8yUjFGYVEycDZSa055VmxSdCIsImVtYWlsIjoiZGV2dG9vbHNAY3Nhcy5jeiJ9LCJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzNCbGRISm9ZWFJ2Ym5OcGRITnZiSFYwYVc5dWMyTjZNV3hxTlhrNGFUTnFNbTF3Ym5OemVuQmphbVpvZDI1dWRuQnpPamxPVUUxRVZWRTFSelJKT1ZRNFN6bEhTMDFZTkRreVVFZ3lRMDA1UlZSV1RUY3dNVXRVU0RoTVRVRlpUazFOV0VaSVJFZFVUVWhMUmtkWVFrWkNSMWc9IiwiZW1haWwiOiJwaGF0b25AY3Nhcy5jeiJ9fX0=
