---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-observability
      endpoint: minio.minio-s3.svc.cluster.local
      access_key: FkKGAiWBt9QKrKIi
      secret_key: L0ZoMcdvDXm6qQneE9UqyoC1YBfSTXE3
      insecure: false
      #signature_version2: false
      #put_user_metadata: {}
      http_config:
        idle_conn_timeout: 0s
        insecure_skip_verify: true
