---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: projects
    server: ''
  source:
    path: _INSTALL_/01-ACM/configure-observability/optional-minio/minio-operator
    repoURL: 'https://github.com/hates52/ACM-multicluster.git'
    targetRevision: HEAD
  sources: []
  project: default
