---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx-sample
spec:
  selector:
    matchLabels:
      app: nginx-sample
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
