---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE_NAME
  objref:
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    name: nginx-sample 

namespace: nginx-sample

resources:
- namespace.yaml
- application.yaml
- channel.yaml
- subscription.yaml
- placementrule.yaml
