---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: lab1
  labels:
    app: $(SAS_NAME)
  annotations:
    apps.open-cluster-management.io/github-path: applications/$(SAS_NAME)
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: $(SAS_NAME)/githubcom-cloud-for-you-acm-multicluster
  placement:
    placementRef:
      kind: PlacementRule
      name: lab1
