---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: lab1
  labels:
    app: nginx-sample
  annotations:
    apps.open-cluster-management.io/github-path: applications/$(NAMESPACE_NAME)
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: $(NAMESPACE_NAME)/githubcom-hates52-acm-multicluster
  placement:
    placementRef:
      kind: PlacementRule
      name: lab1
