---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: projects-placement-rule-lab1
  labels:
    app: projects
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: lab1

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: projects-placement-rule-lab2
  labels:
    app: projects
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: lab2
