---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: projects
    server: ''
  source:
    path: gitops/projects
    repoURL: 'https://github.com/Cloud-for-You/ACM-multicluster.git'
    targetRevision: HEAD
  sources: []
  project: default
