---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: minio-s3
spec:
  selector:
    matchLabels:
      app: minio-s3
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
