apiVersion: ops.csas.cz/v1
kind: Project
metadata:
  name: nginx-sample
  label:
    app: project
spec:
  description: ACM project pro nginx-sample aplikaci
  environments:
    - name: rakosnicek
      type: acm
      #sccRanges: 1001020000/10000      #  LAB1-old: 1000990000/10000   LAB2-old: 1001000000/10000

  limits:
    - max:
        cpu: '2'
        memory: 4Gi
      type: Pod
    - defaultRequest:
        cpu: 250m
        memory: 512Mi
      max:
        cpu: '2'
        memory: 4Gi
      type: Container
    - max:
        storage: 2Gi
      type: PersistentVolumeClaim
